//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class adaptationDialog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adaptationDialog()
        {
            this.adaptationSubtitles = new HashSet<adaptationSubtitle>();
        }
    
        public int dialogIntno { get; set; }
        public long dubbSheetHdrIntno { get; set; }
        public short sceneNo { get; set; }
        public Nullable<short> dialogNo { get; set; }
    
        public virtual dubbingSheetHdr dubbingSheetHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adaptationSubtitle> adaptationSubtitles { get; set; }
    }
}
