//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class adaptationScene
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adaptationScene()
        {
            this.sceneDialogs = new HashSet<sceneDialog>();
        }
    
        public int sceneIntno { get; set; }
        public long orderTrnHdrIntno { get; set; }
        public int sceneNo { get; set; }
        public string summary { get; set; }
    
        public virtual orderAdaptation orderAdaptation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sceneDialog> sceneDialogs { get; set; }
    }
}
