//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class agreement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agreement()
        {
            this.agreements1 = new HashSet<agreement>();
            this.agreementSpecs = new HashSet<agreementSpec>();
            this.agreementTerms = new HashSet<agreementTerm>();
            this.agreementWorks = new HashSet<agreementWork>();
        }
    
        public long agreementIntno { get; set; }
        public long clientIntno { get; set; }
        public string agreementType { get; set; }
        public string agreementName { get; set; }
        public string othAgreementName { get; set; }
        public Nullable<long> refAgreementIntno { get; set; }
        public System.DateTime fromDate { get; set; }
        public short agreementDuration { get; set; }
        public string durationUom { get; set; }
        public Nullable<System.DateTime> thruDate { get; set; }
        public string remarks { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agreement> agreements1 { get; set; }
        public virtual agreement agreement1 { get; set; }
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agreementSpec> agreementSpecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agreementTerm> agreementTerms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agreementWork> agreementWorks { get; set; }
    }
}
