//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class agreementTerm
    {
        public long termIntno { get; set; }
        public long agreementIntno { get; set; }
        public short sortOrder { get; set; }
        public string termDesc { get; set; }
    
        public virtual agreement agreement { get; set; }
    }
}
