//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class audioSampleHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public audioSampleHdr()
        {
            this.audioSampleDtls = new HashSet<audioSampleDtl>();
        }
    
        public long audioSampleHdrIntno { get; set; }
        public string Title { get; set; }
        public long voiceActorIntno { get; set; }
        public long tagTemplateHdrIntno { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public string FileName { get; set; }
        public string FileUrl { get; set; }
        public string Studio { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<audioSampleDtl> audioSampleDtls { get; set; }
        public virtual tagTemplateHdr tagTemplateHdr { get; set; }
        public virtual voiceActor voiceActor { get; set; }
    }
}
