//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrierSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public carrierSchedule()
        {
            this.shipments = new HashSet<shipment>();
        }
    
        public long carrierScheduleIntno { get; set; }
        public string weekDay { get; set; }
        public long carrierIntno { get; set; }
        public System.TimeSpan flightTime { get; set; }
        public string departure { get; set; }
        public string destination { get; set; }
        public bool status { get; set; }
    
        public virtual carrier carrier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shipment> shipments { get; set; }
    }
}
