//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class chrCastListHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chrCastListHdr()
        {
            this.chrCastListDtls = new HashSet<chrCastListDtl>();
        }
    
        public long chrCastListHdrIntno { get; set; }
        public long workCharacterIntno { get; set; }
        public long clientIntno { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chrCastListDtl> chrCastListDtls { get; set; }
        public virtual client client { get; set; }
        public virtual workCharacter workCharacter { get; set; }
    }
}
