//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class chrCastListDtl
    {
        public long chrCastListDtlIntno { get; set; }
        public long chrCastListHdrIntno { get; set; }
        public long voiceActorIntno { get; set; }
        public double Match { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ClientRank { get; set; }
        public string ClientComments { get; set; }
    
        public virtual chrCastListHdr chrCastListHdr { get; set; }
        public virtual voiceActor voiceActor { get; set; }
    }
}
