//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class chrTemplateHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chrTemplateHdr()
        {
            this.chrTemplateDtls = new HashSet<chrTemplateDtl>();
        }
    
        public long chrTemplateHdrIntno { get; set; }
        public long workCharacterIntno { get; set; }
        public long tagTemplateHdrIntno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chrTemplateDtl> chrTemplateDtls { get; set; }
        public virtual workCharacter workCharacter { get; set; }
        public virtual tagTemplateHdr tagTemplateHdr { get; set; }
    }
}
