//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contact()
        {
            this.agreementWorks = new HashSet<agreementWork>();
        }
    
        public long contactIntno { get; set; }
        public string contactParty { get; set; }
        public long partyIntno { get; set; }
        public string salutation { get; set; }
        public string contactName { get; set; }
        public string othContactName { get; set; }
        public string contactTitle { get; set; }
        public string contactPhoneNbr { get; set; }
        public string contactEmailAddr { get; set; }
        public string mailingAddr { get; set; }
        public string remarks { get; set; }
        public bool status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agreementWork> agreementWorks { get; set; }
    }
}
