//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class costCenter
    {
        public long costCenterIntno { get; set; }
        public long workIntno { get; set; }
        public string costCenterType { get; set; }
        public string costCenterName { get; set; }
        public string othCostCenterName { get; set; }
        public string accountNo { get; set; }
        public bool status { get; set; }
    
        public virtual agreementWork agreementWork { get; set; }
    }
}
