//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliveryFeedback
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public deliveryFeedback()
        {
            this.feedbackActions = new HashSet<feedbackAction>();
        }
    
        public long feedbackIntno { get; set; }
        public long orderTrnHdrIntno { get; set; }
        public string feedbackType { get; set; }
        public System.DateTime receivedDate { get; set; }
        public string clientRefNo { get; set; }
        public string feedbackDesc { get; set; }
        public string refLocation { get; set; }
        public string remarks { get; set; }
        public bool status { get; set; }
    
        public virtual orderTrnHdr orderTrnHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedbackAction> feedbackActions { get; set; }
    }
}
