//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dialog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dialog()
        {
            this.subtitles = new HashSet<subtitle>();
        }
    
        public long dialogIntno { get; set; }
        public long sceneIntno { get; set; }
        public short dialogNo { get; set; }
        public string startTimeCode { get; set; }
        public string endTimeCode { get; set; }
        public bool isTaken { get; set; }
        public long startSecond { get; set; }
        public long endSecond { get; set; }
    
        public virtual scene scene { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subtitle> subtitles { get; set; }
    }
}
