//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dubbDomain
    {
        public long domainIntno { get; set; }
        public string domainName { get; set; }
        public string domainCode { get; set; }
        public string domainValue { get; set; }
        public string userMessage { get; set; }
        public string valueUsage { get; set; }
        public string langCode { get; set; }
        public short sortOrder { get; set; }
        public short minAccessLevel { get; set; }
        public bool status { get; set; }
    }
}
