//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dubbingTrnDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dubbingTrnDtl()
        {
            this.dubbingAppointments = new HashSet<dubbingAppointment>();
        }
    
        public long dubbTrnDtlIntno { get; set; }
        public long dubbTrnHdrIntno { get; set; }
        public long orderTrnHdrIntno { get; set; }
        public Nullable<System.DateTime> dubbingDate { get; set; }
        public string studioNo { get; set; }
        public Nullable<long> supervisor { get; set; }
        public Nullable<long> soundTechnician { get; set; }
        public Nullable<long> assistant { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dubbingAppointment> dubbingAppointments { get; set; }
        public virtual dubbingTrnHdr dubbingTrnHdr { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual employee employee2 { get; set; }
        public virtual orderTrnHdr orderTrnHdr { get; set; }
    }
}
