//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dubbingSheetDtl
    {
        public long dubbSheetDtlIntno { get; set; }
        public long orderTrnHdrIntno { get; set; }
        public long dubbSheetHdrIntno { get; set; }
        public short sceneNo { get; set; }
        public bool isTaken { get; set; }
        public string studioNo { get; set; }
        public Nullable<long> supervisor { get; set; }
        public Nullable<long> soundTechnician { get; set; }
        public Nullable<long> assistant { get; set; }
        public Nullable<System.DateTime> takenTimeStamp { get; set; }
    
        public virtual dubbingSheetHdr dubbingSheetHdr { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual employee employee2 { get; set; }
        public virtual orderTrnHdr orderTrnHdr { get; set; }
    }
}
