//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dubbingTrnDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dubbingTrnDtl()
        {
            this.studioEpisodes = new HashSet<studioEpisode>();
        }
    
        public long dubbTrnDtlIntno { get; set; }
        public long dubbTrnHdrIntno { get; set; }
        public long workIntno { get; set; }
        public long orderTrnHdrIntno { get; set; }
        public int episodeNo { get; set; }
    
        public virtual agreementWork agreementWork { get; set; }
        public virtual dubbingTrnHdr dubbingTrnHdr { get; set; }
        public virtual orderTrnHdr orderTrnHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studioEpisode> studioEpisodes { get; set; }
    }
}
