//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedbackAction
    {
        public long actionIntno { get; set; }
        public long feedbackIntno { get; set; }
        public string actionParty { get; set; }
        public string actionToBeTaken { get; set; }
        public Nullable<System.DateTime> actionDate { get; set; }
        public string checkedBy { get; set; }
        public Nullable<System.DateTime> checkedDate { get; set; }
        public bool status { get; set; }
    
        public virtual deliveryFeedback deliveryFeedback { get; set; }
    }
}
