//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class logActor
    {
        public long logIntno { get; set; }
        public int logYear { get; set; }
        public int logMonth { get; set; }
        public long clientIntno { get; set; }
        public string clientName { get; set; }
        public long workIntno { get; set; }
        public string workName { get; set; }
        public string workType { get; set; }
        public int totalMainActors { get; set; }
        public int totalMainActorsCharges { get; set; }
        public int highestMainActorCharges { get; set; }
        public int lowestMainActorCharges { get; set; }
        public int totalOtherActors { get; set; }
        public int totalOtherActorsCharges { get; set; }
        public int avgOtherActorCharges { get; set; }
        public int lastUpdate { get; set; }
    }
}
