//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class logOrder
    {
        public long logIntno { get; set; }
        public int logYear { get; set; }
        public int logMonth { get; set; }
        public long clientIntno { get; set; }
        public string clientName { get; set; }
        public long workIntno { get; set; }
        public string workName { get; set; }
        public string workType { get; set; }
        public int totalEpisodesReceived { get; set; }
        public int totalEpisodesDubbed { get; set; }
        public int totalEpisodesUploaded { get; set; }
        public int totalEpisodesShipped { get; set; }
        public int totalScenesDubbed { get; set; }
        public Nullable<int> lastEpisodeReceived { get; set; }
        public Nullable<int> lastEpisodeDubbed { get; set; }
        public Nullable<int> lastEpisodeUploaded { get; set; }
        public Nullable<int> lastEpisodeShipped { get; set; }
        public int totalDubbingCharges { get; set; }
        public int totalTranslationCharges { get; set; }
        public int totalAdaptationCharges { get; set; }
        public int totalMeCharges { get; set; }
        public int totalOtherCharges { get; set; }
        public System.DateTime lastUpdate { get; set; }
    }
}
