//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class logWork
    {
        public long logIntno { get; set; }
        public long clientIntno { get; set; }
        public string clientName { get; set; }
        public long workIntno { get; set; }
        public string workName { get; set; }
        public string workType { get; set; }
        public string workNationality { get; set; }
        public Nullable<System.DateTime> contractedDate { get; set; }
        public Nullable<int> contractedYear { get; set; }
        public Nullable<int> contractedMonth { get; set; }
        public Nullable<System.DateTime> endorsedDate { get; set; }
        public Nullable<int> endorsedYear { get; set; }
        public Nullable<int> endorsedMonth { get; set; }
        public System.DateTime lastUpdate { get; set; }
        public string updatedBy { get; set; }
    }
}
