//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderTrnDtl
    {
        public long orderTrnDtlIntno { get; set; }
        public long orderTrnHdrIntno { get; set; }
        public string activityType { get; set; }
        public long empIntno { get; set; }
        public string providedService { get; set; }
        public Nullable<int> totalMinutes { get; set; }
        public string timeRating { get; set; }
        public string qualityRating { get; set; }
    
        public virtual orderTrnHdr orderTrnHdr { get; set; }
    }
}
