//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderBatchTrnHdr
    {
        public long orderBatchTrnIntno { get; set; }
        public long orderIntno { get; set; }
        public long workIntno { get; set; }
        public string trnType { get; set; }
        public int fromEpisode { get; set; }
        public int thruEpisode { get; set; }
        public System.DateTime trnDate { get; set; }
        public long empIntno { get; set; }
        public string trnDesc { get; set; }
        public string remarks { get; set; }
        public string updatedBy { get; set; }
        public System.DateTime lastUpdated { get; set; }
        public bool status { get; set; }
    
        public virtual agreementWork agreementWork { get; set; }
        public virtual employee employee { get; set; }
        public virtual workOrder workOrder { get; set; }
    }
}
