//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentDetail
    {
        public long paymentDtlIntno { get; set; }
        public long paymentHdrIntno { get; set; }
        public short episodeNo { get; set; }
        public Nullable<int> totalScenes { get; set; }
        public Nullable<int> adjustedTotalScenes { get; set; }
        public int unitRate { get; set; }
        public int amount { get; set; }
    
        public virtual payment payment { get; set; }
    }
}
