//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentTemp
    {
        public long tempIntno { get; set; }
        public long personIntno { get; set; }
        public string personName { get; set; }
        public long workIntno { get; set; }
        public string workName { get; set; }
        public System.DateTime trnDate { get; set; }
        public int totalUnits { get; set; }
        public Nullable<long> refPaymentIntno { get; set; }
    }
}
