//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public long paymentHdrIntno { get; set; }
        public long dubbTrnHdrIntno { get; set; }
        public long workIntno { get; set; }
        public string costCenterType { get; set; }
        public Nullable<long> voiceActorIntno { get; set; }
        public Nullable<long> empIntno { get; set; }
        public string anonymousName { get; set; }
        public short episodeNo { get; set; }
        public int totalScenes { get; set; }
        public int adjustedTotalScenes { get; set; }
        public int unitRate { get; set; }
        public string paymentDesc { get; set; }
        public int totalAmount { get; set; }
        public string currencyCode { get; set; }
        public int deduction { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public string remarks { get; set; }
        public bool status { get; set; }
        public string accountNo { get; set; }
    
        public virtual agreementWork agreementWork { get; set; }
        public virtual dubbingTrnHdr dubbingTrnHdr { get; set; }
        public virtual employee employee { get; set; }
        public virtual voiceActor voiceActor { get; set; }
    }
}
