//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public payment()
        {
            this.paymentDetails = new HashSet<paymentDetail>();
        }
    
        public long paymentHdrIntno { get; set; }
        public long dubbTrnHdrIntno { get; set; }
        public long workIntno { get; set; }
        public string costCenterType { get; set; }
        public Nullable<long> voiceActorIntno { get; set; }
        public Nullable<long> empIntno { get; set; }
        public string anonymousName { get; set; }
        public string paymentDesc { get; set; }
        public int totalAmount { get; set; }
        public string currencyCode { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public string remarks { get; set; }
        public bool status { get; set; }
    
        public virtual agreementWork agreementWork { get; set; }
        public virtual dubbingTrnHdr dubbingTrnHdr { get; set; }
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paymentDetail> paymentDetails { get; set; }
        public virtual voiceActor voiceActor { get; set; }
    }
}
