//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentsDueVW
    {
        public long workIntno { get; set; }
        public string workName { get; set; }
        public long voiceActorIntno { get; set; }
        public string actorName { get; set; }
        public Nullable<System.DateTime> dubbingDate { get; set; }
        public Nullable<int> totalUnits { get; set; }
    }
}
