//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shipment()
        {
            this.shipmentDetails = new HashSet<shipmentDetail>();
        }
    
        public long shipmentIntno { get; set; }
        public Nullable<long> carrierIntno { get; set; }
        public System.DateTime shipmentDate { get; set; }
        public string remarks { get; set; }
        public bool status { get; set; }
        public long clientIntno { get; set; }
    
        public virtual carrier carrier { get; set; }
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shipmentDetail> shipmentDetails { get; set; }
    }
}
