//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class studio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public studio()
        {
            this.studioDtls = new HashSet<studioDtl>();
            this.dubbingAppointments = new HashSet<dubbingAppointment>();
        }
    
        public long studioIntno { get; set; }
        public long dubbTrnHdrIntno { get; set; }
        public string studioNo { get; set; }
        public Nullable<long> supervisor { get; set; }
        public Nullable<long> sound { get; set; }
        public bool status { get; set; }
        public int srl { get; set; }
    
        public virtual dubbingTrnHdr dubbingTrnHdr { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studioDtl> studioDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dubbingAppointment> dubbingAppointments { get; set; }
    }
}
