//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class studioDtl
    {
        public long studioDtlsIntno { get; set; }
        public long studioIntno { get; set; }
        public long workIntno { get; set; }
        public bool isDefault { get; set; }
    
        public virtual agreementWork agreementWork { get; set; }
        public virtual studio studio { get; set; }
    }
}
