//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class studioEpisode
    {
        public long studioEpisodeIntno { get; set; }
        public long studioIntno { get; set; }
        public long orderTrnDtlIntno { get; set; }
    
        public virtual orderTrnDtl orderTrnDtl { get; set; }
        public virtual studio studio { get; set; }
    }
}
