//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class subtitle
    {
        public long subtitleIntno { get; set; }
        public long dialogIntno { get; set; }
        public short subtitleNo { get; set; }
        public Nullable<long> workCharacterIntno { get; set; }
        public string characterName { get; set; }
        public string scentence { get; set; }
        public string startTimeCode { get; set; }
        public string endTimeCode { get; set; }
    
        public virtual dialog dialog { get; set; }
        public virtual workCharacter workCharacter { get; set; }
    }
}
