//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tagTemplateDtl
    {
        public long tagTemplateDtlIntno { get; set; }
        public long tagTemplateHdrIntno { get; set; }
        public int tagId { get; set; }
        public int MinScore { get; set; }
        public Nullable<int> Weight { get; set; }
    
        public virtual tag tag { get; set; }
        public virtual tagTemplateHdr tagTemplateHdr { get; set; }
    }
}
