//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class workCharacter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public workCharacter()
        {
            this.dubbingSheetHdrs = new HashSet<dubbingSheetHdr>();
            this.workActors = new HashSet<workActor>();
        }
    
        public long workCharacterIntno { get; set; }
        public long workIntno { get; set; }
        public short sortOrder { get; set; }
        public string characterType { get; set; }
        public string characterGender { get; set; }
        public string characterName { get; set; }
        public string othCharacterName { get; set; }
        public string nickName { get; set; }
        public string characterDesc { get; set; }
        public string remarks { get; set; }
    
        public virtual agreementWork agreementWork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dubbingSheetHdr> dubbingSheetHdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workActor> workActors { get; set; }
    }
}
