//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dubbingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class workOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public workOrder()
        {
            this.orderBatchTrnHdrs = new HashSet<orderBatchTrnHdr>();
            this.orderTrnHdrs = new HashSet<orderTrnHdr>();
        }
    
        public long orderIntno { get; set; }
        public long clientIntno { get; set; }
        public long workIntno { get; set; }
        public short fromEpisode { get; set; }
        public short thruEpisode { get; set; }
        public System.DateTime receivedDate { get; set; }
        public string priority { get; set; }
        public Nullable<System.DateTime> expectedDeliveryDate { get; set; }
        public Nullable<bool> allowFirstDubbing { get; set; }
        public string remarks { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> lastUpdated { get; set; }
        public string status { get; set; }
    
        public virtual agreementWork agreementWork { get; set; }
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderBatchTrnHdr> orderBatchTrnHdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderTrnHdr> orderTrnHdrs { get; set; }
    }
}
