CREATE TABLE [dbo].[orderTrnHdrs] (
    [orderTrnHdrIntno]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [workIntno]            BIGINT        NOT NULL,
    [orderIntno]           BIGINT        NOT NULL,
    [episodeNo]            SMALLINT      NOT NULL,
    [priority]             NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
    [orderReceivedDate]    DATETIME      NULL,
    [expectedDeliveryDate] DATETIME      NULL,
    [allowFirstDubbing]    BIT           NULL,
    [startTranslation]     DATETIME      NULL,
    [endTranslation]       DATETIME      NULL,
    [startAdaptation]      DATETIME      NULL,
    [endAdaptation]        DATETIME      NULL,
    [startDischarge]       DATETIME      NULL,
    [endDischarge]         DATETIME      NULL,
    [plannedDubbing]       DATETIME      NULL,
    [startDubbing]         DATETIME      NULL,
    [endDubbing]           DATETIME      NULL,
    [startMixage]          DATETIME      NULL,
    [endMixage]            DATETIME      NULL,
    [startMontage]         DATETIME      NULL,
    [endMontage]           DATETIME      NULL,
    [plannedUpload]        DATETIME      NULL,
    [shipmentLowRes]       DATETIME      NULL,
    [plannedShipment]      DATETIME      NULL,
    [shipmentFinal]        DATETIME      NULL,
    [status]               NVARCHAR (50) COLLATE Latin1_General_CI_AS NOT NULL,
    CONSTRAINT [PK_orderTrnHdrs] PRIMARY KEY CLUSTERED ([orderTrnHdrIntno] ASC),
    CONSTRAINT [FK_orderTrnHdrs_agreementWorks] FOREIGN KEY ([workIntno]) REFERENCES [dbo].[agreementWorks] ([workIntno]),
    CONSTRAINT [FK_orderTrnHdrs_workOrders] FOREIGN KEY ([orderIntno]) REFERENCES [dbo].[workOrders] ([orderIntno])
);

